version: "3.7"

services:
  database-docprocai:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - "9932:5432"
    volumes:
      - searchdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=search-service
  app-docprocai:
    build:
      context: ./../docprocai_service
      dockerfile: Dockerfile
    restart: always
    container_name: docprocai_service
    ports:
      - "9900:9900"
      - "9901:9901"
volumes:
  searchdata:
networks:
  default:
      name: dapr-network
      external: true